language: python
python:
  - 3.7-dev
services:
  - postgresql
install:
  - pip install pipenv
  - pipenv install --skip-lock --system --dev
before_script:
  - psql -c 'create database travisci;' -U postgres
  - python app/manage.py makemigrations --settings=gss.settings.ci
  - python app/manage.py migrate --settings=gss.settings.ci
  - python app/manage.py initgroups --settings=gss.settings.ci
script:
  - pytest