language: python
python:
  - 3.7-dev
services:
  - postgresql
install:
  - pip install pipenv
  - pipenv lock
  - pipenv sync
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py test