language: python
python:
  - 3.7-dev
services:
  - postgresql
install:
  - pip install pipenv
  - pipenv lock
  - pipenv sync
before_script:
  - psql -c 'create database travisci;' -U postgres
  - python app/manage.py makemigrations --settings=gss.settings.ci
  - python app/manage.py migrate --settings=gss.settings.ci
script:
  - python app/manage.py test --settings=gss.settings.ci