version: '3.7'

services:
  webpack:
    build: 
      context: ./
      dockerfile: ./docker/webpack/Dockerfile
    volumes:
      - assets_volume:/usr/src/app/assets/dist
  web:
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - assets_volume:/usr/src/app/assets/dist
    command: gunicorn gss.wsgi:application --bind 0.0.0.0:8000
    expose: 
      - 8000
    depends_on:
      - db
      - webpack
  db:
    image: postgres:11.1-alpine
  nginx:
    build: 
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
    - 1337:80
    depends_on:
    - web
  portainer:
    image: portainer/portainer
    ports:
      - "9000"
    networks:
      - portainer-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes: 
  assets_volume:
  static_volume:
  media_volume:
networks:
  portainer-net: