# Generated by Django 2.1.5 on 2019-01-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UnitAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action_type', models.CharField(choices=[(0, 'снятие'), (1, 'неисправность')], max_length=1)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='manufacturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.UnitCreator'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('unit_number', 'manufacturer_id')},
        ),
    ]
