# Generated by Django 2.1.5 on 2019-01-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaction',
            name='action_type',
            field=models.CharField(choices=[(0, 'removals'), (1, 'failures'), (2, 'induced')], max_length=1),
        ),
    ]
