# Generated by Django 2.1.5 on 2019-01-12 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircarts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField()),
                ('aircart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircarts.Aircart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField()),
                ('aircart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircarts.Aircart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Included',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField()),
                ('aircart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircarts.Aircart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField()),
                ('aircart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircarts.Aircart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='removal',
            unique_together={('date', 'aircart')},
        ),
        migrations.AlterUniqueTogether(
            name='included',
            unique_together={('date', 'aircart')},
        ),
        migrations.AlterUniqueTogether(
            name='fh',
            unique_together={('date', 'aircart')},
        ),
        migrations.AlterUniqueTogether(
            name='failture',
            unique_together={('date', 'aircart')},
        ),
    ]
